name: Github_Actions_Study

on: 
  push:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: create-vite-env
        run: |
          chmod 777 -R front
          cat <<EOL > front/.env
          VITE_PORTONE_STOREID=${{ secrets.VITE_PORTONE_STOREID }}
          VITE_PORTONE_API_KEY=${{ secrets.VITE_PORTONE_API_KEY }}
          EOL
          cat front/.env
          
      - name: create-application-secret
        run: |
          chmod 777 -R back
          cat <<EOL > back/src/main/resources/application-secret.yml
          spring:
            config:
              activate:
                on-profile: secret
          
            datasource:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://${{ secrets.EC2_PUBLIC_IP }}:3306/${{ secrets.DATABASE_NAME }}
              username: ${{ secrets.DATABASE_USERNAME }}
              password: ${{ secrets.DATABASE_PASSWORD }}
          
          ---
          spring:
            config:
              activate:
                on-profile: common        
          
          jwt:
            secret: ${{ secrets.JWT_SECRET }}
          EOL
          cat back/src/main/resources/application-secret.yml
          
      - name: print-directory
        run: |
          ls -a front
          ls -a back/src/main/resources

      - name: DockerHub-LOGIN
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build-And-Push-React-App
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/carecheck-react-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/carecheck-react-app:latest
          
      - name: Build-And-Push-Spring-App
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/carecheck-spring-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/carecheck-spring-app:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/carecheck-react-app:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/carecheck-spring-app:latest
            cd /home/ubuntu/project
            sudo docker-compose -f project-compose.yml down
            sudo docker-compose -f project-compose.yml up -d





          
